name: CI pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U "poetry" 
          poetry install

      - name: Static code analysis
        run: |
          poetry run ruff check casrl
          poetry run mypy casrl --explicit-package-bases

      - name: Run tests
        run: |
          poetry run pytest tests

      - name: Generate coverage badge
        run: |
          COVERAGE_PERCENTAGE=$(poetry run pytest --cov | awk '$1 == "TOTAL" {print $NF+0}')
          mkdir coverage
          curl -s "https://img.shields.io/badge/coverage-$COVERAGE_PERCENTAGE%25-brightgreen" > coverage/coverage.svg

      - name: Host coverage badge on gh pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./coverage
