name: CI pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U "poetry" 
          poetry install

      - name: Static code analysis
        run: |
          poetry run ruff check casrl
          poetry run mypy casrl --explicit-package-bases

      - name: Run tests
        run: |
          poetry run pytest tests